version: '2.1'
services:
    redis:
        image: 'redis:3.2.7'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - airflow-postgresql-volume:/var/lib/postgresql/data

    webserver:
        image: clellmann/kriging-airflow:1.10.4
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=S7ZRZega9qzb5CB96SqAsASbvncNcnZ0fBfbqtIgiqA=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        env_file:
            - app.env
        volumes:
            - C:\Users\chris\OneDrive\Dokumente\Master\'Modul 60100'\particle-kriging\data:/usr/local/airflow/results
            #- ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "9090:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: clellmann/kriging-airflow:1.10.4
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        env_file:
            - app.env
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: clellmann/kriging-airflow:1.10.4
        restart: always
        depends_on:
            - webserver
        #volumes:
            #- ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=S7ZRZega9qzb5CB96SqAsASbvncNcnZ0fBfbqtIgiqA=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        env_file:
            - app.env
        volumes:
            - C:\Users\chris\OneDrive\Dokumente\Master\'Modul 60100'\particle-kriging\data:/usr/local/airflow/results
        command: scheduler

    worker:
        image: clellmann/kriging-airflow:1.10.4
        restart: always
        depends_on:
            - scheduler
        #volumes:
            #- ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=S7ZRZega9qzb5CB96SqAsASbvncNcnZ0fBfbqtIgiqA=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        env_file:
            - app.env
        volumes:
            - C:\Users\chris\OneDrive\Dokumente\Master\'Modul 60100'\particle-kriging\data:/usr/local/airflow/results
        command: worker

volumes:
    airflow-postgresql-volume:
      external: true
    airflow-results:
      external: true
